### ISSUE TITLE
Add RPC error handling to `Call()` in session.go

### ISSUE THREAD

**Issue by rumenvasilev** [nemith/netconf#22]
There's none as indicated in the source :)
That doesn't help with using the library though.

I came up with a generic (basic) handling, leveraging the new multierror support in go 1.20, so it at least returns the error to the caller. Not great (might be better to sugarcoat it a bit, so it's more streamlined, like AWS SDK's awserrors for instance), but better than nothing :)

For that to work though, the project would need to be "upgraded" from 1.16 to 1.20 (no more ioutil as a start).

LMK if you want me to open a PR with suggestions.

**Comment by nemith** [comment]
Also see https://github.com/nemith/netconf/blob/main/TODO.md  The list is still pretty long :)

**Comment by nemith** [comment]
This functionality has been added.  Let me know if it works for you.
