### ISSUE TITLE
Add a `Commit()` method, or generic one?

### ISSUE THREAD

**Issue by rumenvasilev** [nemith/netconf#23]
In JunOS, one has to commit the configuration after `EditConfig()`. That method isn't available in the library though, nor I found an alternative to reuse. I haven't tested that on other brands yet, but in case they don't have the "commit" call, perhaps an alternative for the library could be to add a more generic method, that could be used for simple RPC messages.

The XML structure of the commit call (for JunOS, documented [here](https://www.juniper.net/documentation/us/en/software/junos/netconf/topics/task/netconf-configuration-committing.html)) is:

```xml
<rpc>
    <commit/>
</rpc>
```

What I came up with to solve my use case is:

```go
type basicReq struct {
	XMLName xml.Name
}

func (s *Session) Commit(ctx context.Context) error {
	req := basicReq{
		XMLName: xml.Name{Local: "commit"},
	}
	var resp OKResp
	return s.Call(ctx, &req, &resp)
}
```

Clearly that `Commit()` method could be changed to take "commit" as input parameter and use it in the req constructor:

```go
func (s *Session) Commit(ctx context.Context, message string) error {
	req := basicReq{
		XMLName: xml.Name{Local: message},
	}
	...
}
```

**Comment by nemith** [comment]
I actually have a WIP PR that adds (all?) off the RFC6241 operations.  I think it was blocked on some more advanced testing.

**Comment by rumenvasilev** [comment]
If you share that, I might be able to run some tests against vSRX.

**Comment by nemith** [comment]
Well we have cSRX as and inttest target which would be the appropriate place to start for testing.

**Comment by nemith** [comment]
@rumenvasilev Can you check the attached PR for your functionality?
