### ISSUE TITLE
Chunk reader gets stuck in a loop at the end of a frame

### ISSUE THREAD

**Issue by nights99** [nemith/netconf#69]
I like this new repository, and I'm almost ready to switch over from the old repo, but I have one remaining issue: with the netconf server I'm using, I regularly see the code get stuck in a loop at the end of a chunked response. I looked into this a while back and this diff seems to fix it, but I'm not sure if its the right fix; if it is, happy to do a PR:

```
@@ -268,8 +275,11 @@ func (r *chunkReader) Close() error {
                        }
                }
 
-               if _, err := r.r.Discard(r.chunkLeft); err != nil {
+               // Gets permanently stuck without this
+               if n, err := r.r.Discard(r.chunkLeft); err != nil {
                        return err
+               } else {
+                       r.chunkLeft -= n
                }
        }
 }
```

**Comment by nemith** [comment]
This seems legit. Also seems like something that should be done regardless of the error returned (so no else).

My main testing in prod is against Juniper devices that don't even support chunked mode.  I will look at this soon.


Thanks for the report!

**Comment by nights99** [comment]
Thanks, yeah I'm mostly testing against Cisco XR devices, so I'll likely hit different things - hopefully provides some useful extra testing.

I think I can hit the hang with a testcase added to `inttest/ssh_test.go` - but only when run against an XR device. I think there might be one or two options in Cisco DevNet to test against, but I should probably check the licensing further first.

**Comment by nemith** [comment]
Yeah inttesting is crap due to licensing.   I have eos and junos as "private" docker images, but anything that runs in a VM cannot be ran on Github Runners (right now).  

I need to figure out something better longer term, but I appreciate the testing.  It looks like a clear issue, if you want to submit a PR that would be appreciated, if not i will try to get to in the next couple of days.

**Comment by nemith** [comment]
I finally started looking into this and it is interesting.  Is there anyway you can capture this error.  You can use the  the `DebugCapture` https://github.com/nemith/netconf/blob/c67f895db57ed076c04f9f7156de0ef6e914f28c/transport/frame.go#L89.

I think i understand what is going on but I would like to verify.

**Comment by nemith** [comment]
Can you also test the above pull request?

**Comment by nights99** [comment]
Happy to say the problem is fixed on the branch.

Also attaching the capture logs here.

[2024-01-27T115614Z.in.txt](https://github.com/nemith/netconf/files/14072204/2024-01-27T11.56.14Z.in.txt)
[2024-01-27T115614Z.out.txt](https://github.com/nemith/netconf/files/14072205/2024-01-27T11.56.14Z.out.txt)

Thanks for looking into this.
